import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { Merriweather } from "next/font/google";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";

const merriweather = Merriweather({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${merriweather.className}`}>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
