import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { Merriweather } from "next/font/google";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import ProfileNav from "@/components/ProfileNav";
import { AppProvider } from "../context";

const merriweather = Merriweather({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "MarketPlace",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <AppProvider>
          <body className={`${merriweather.className} bg-[#f9fbe7]`}>
            <ProfileNav />
            <div className="mt-[5px] py-[20px] sm:px-[50px] px-[20px]">
              {children}
            </div>
          </body>
        </AppProvider>
      </html>
    </ClerkProvider>
  );
}
