import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { Merriweather } from "next/font/google";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import Navbar from "@/components/Navbar";
import { AppProvider } from "../context";

const merriweather = Merriweather({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "MarketPlace",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <AppProvider>
          <body className={`${merriweather.className}`}>
            <Navbar />
            <div className="mt-[20px]">{children}</div>
          </body>
        </AppProvider>
      </html>
    </ClerkProvider>
  );
}
