import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { Merriweather } from "next/font/google";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import Navbar from "@/components/Navbar";

const merriweather = Merriweather({
  weight: "400",
  subsets: ["latin"],
});

export const metadata = {
  title: "MarketPlace",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${merriweather.className} bg-[#f9fbe7]`}>
          <Navbar />
          <div className="mt-[20px]">{children}</div>
        </body>
      </html>
    </ClerkProvider>
  );
}
